In [2]:
#dependencies and setup
import pandas as pd
import numpy as np

#files to read
d2015 = "Sheets/2015.csv"
d2016 = "Sheets/2016.csv"
d2017 = "Sheets/2017.csv"
d2018 = "Sheets/2018.csv"
d2019 = "Sheets/2019.csv"

#read yearly data files
data_15 = pd.read_csv(d2015)
data_16 = pd.read_csv(d2016)
data_17 = pd.read_csv(d2017)
data_18 = pd.read_csv(d2018)
data_19 = pd.read_csv(d2019)

In [7]:
#2015 extract columns and rearrange columns
df15c = data_15.loc[:,['Happiness Rank', 
                       'Country',
                       'Happiness Score',
                       'Economy (GDP per Capita)',
                       'Family',
                       'Health (Life Expectancy)', 
                       'Freedom', 
                       'Generosity',
                       'Trust (Government Corruption)']]

#2016 extract and rearrange columns
df16c = data_16.loc[:,['Happiness Rank',
                       'Country',
                       'Happiness Score',
                       'Economy (GDP per Capita)',
                       'Family', 
                       'Health (Life Expectancy)',
                       'Freedom',
                       'Generosity', 
                       'Trust (Government Corruption)']]

#2017 extract and rearrange columns
df17c = data_17.loc[:,['Happiness.Rank', 
                       'Country',
                       'Happiness.Score',
                       'Economy..GDP.per.Capita.',
                       'Family',
                       'Health..Life.Expectancy.',
                       'Freedom',
                       'Generosity',
                       'Trust..Government.Corruption.']]

#2018 extract and rearrange columns
df18c = data_18.loc[:,['Happiness.Rank', 
                       'Country',
                       'Happiness.Score',
                       'Economy..GDP.per.Capita.',
                       'Family',
                       'Health..Life.Expectancy.',
                       'Freedom',
                       'Generosity',
                       'Trust..Government.Corruption.']]

#2019 extract and rearrange columns
df19c = data_19.loc[:,['Happiness.Rank', 
                       'Country',
                       'Happiness.Score',
                       'Economy..GDP.per.Capita.',
                       'Family',
                       'Health..Life.Expectancy.',
                       'Freedom',
                       'Generosity',
                       'Trust..Government.Corruption.']]
df19c

,Happiness.Rank,Country,Happiness.Score,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.153,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.252,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.271,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.354,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.322,NaN
...,...,...,...,...,...,...,...,...,...
151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.217,NaN
152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.276,NaN
153,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.158,NaN
154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.235,NaN
155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.202,NaN

In [2]:
#2015 rename columns
df15new= df15c.rename(columns={"Happiness Rank":"Overall rank", 
                               "Country":"Country or Region",
                               "Happiness Score":"Score",
                               "Economy (GDP per Capita)":"GDP per capita",
                               "Family":"Social support",
                               "Health (Life Expectancy)":"Healthy life expectancy",
                               "Freedom":"Freedom to make life choices",
                               "Generosity":"Generosity",
                               "Trust (Government Corruption)": "Perceptions of corruption"})

#2015 replace country names to normalize data
df15new['Country or region'].replace(['Hong Kong S.A.R., China','Taiwan Province of China','Trinidad and Tobago','North Cyprus','Somaliland region'],
                                     ['Hong Kong','Taiwan','Trinidad & Tobago','Northern Cyprus','Somaliland Region'], inplace = True)

In [2]:


#2016 rename columns
df16new = df16c.rename(columns={"Happiness Rank":"Overall rank",
                                "Country":"Country or Region",
                                "Happiness Score":"Score",
                                "Economy (GDP per Capita)":"GDP per capita", 
                                "Family":"Social support",
                                "Health (Life Expectancy)":"Healthy life expectancy",
                                "Freedom":"Freedom to make life choices",
                                "Generosity":"Generosity",
                                "Trust (Government Corruption)": "Perceptions of corruption"})

#2016 replace country names to normalize data
df16new['Country or region'].replace(['Hong Kong S.A.R., China','Taiwan Province of China','Trinidad and Tobago','North Cyprus','Somaliland region'],
                                     ['Hong Kong','Taiwan','Trinidad & Tobago','Northern Cyprus','Somaliland Region'], inplace = True)



#2017 rename columns
df17new = df17c.rename(columns={"Happiness.Rank":"Overall rank", 
                                "Country":"Country or Region",
                                "Happiness.Score":"Score",
                                "Economy..GDP.per.Capita.":"GDP per capita", 
                                "Family":"Social support",
                                "Health..Life.Expectancy.":"Healthy life expectancy",
                                "Freedom":"Freedom to make life choices",
                                "Generosity":"Generosity", 
                                "Trust..Government.Corruption.": "Perceptions of corruption"})

#2017 replace country names to normalize data

df17new['Country or region'].replace(['Hong Kong S.A.R., China','Taiwan Province of China','Trinidad and Tobago','North Cyprus','Somaliland region'],
                                     ['Hong Kong','Taiwan','Trinidad & Tobago','Northern Cyprus','Somaliland Region'], inplace = True)

#merge sheets
df1516 = pd.merge(df15new, df16new, how="outer", on = "Country or region", suffixes=("_15", "_16"))
df1516

df1718 = pd.merge(df17new, data_18, how="outer", on = "Country or region", suffixes=("_17", "_18"))
df1718

df17_19 = pd.merge(df1718, data_19, how="outer", on = "Country or region", suffixes=("", "_19"))
df17_19

df_all= pd.merge(df1516, df17_19, how="outer", on = "Country or region", suffixes=("", ""))
df_all

df_all.to_csv("Sheets/world_happiness.csv", index=False, header=True)